/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package appintro;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean search(ArrayList<Integer> arr,int e){
        if(arr==null)return false;
        for(int i=0;i<arr.size();i++){
            if(arr.get(i)==e)
                return true;
        }
        return false;
    } 
    
}
